### PR TITLE
Sprint_5

### PR DESCRIPTION
**Pull request by Ruurdbk**
Final sprint to be accepted and merged into master branch

### CODE REVIEW

**Comment by boelek** [comment]
Hi Ruurd,
I will download the code today and let you know the results asap.
Boele

**Comment by boelek** [comment]
I didn´t manage to download the code. Can you try again?
Boele

**Comment by boelek** [comment]
Dear Ruurd,
Today we have run your code using the CLI. Everything worked as we discussed during the design. We are very happy with the end product en we have now everything in place to start with the dissemination of the products your code has generated. I expect you will see the results of your work soon in the public domain. Thanks again for your work. Couldn't be more happy...
Boele

**Comment by Ruurdbk** [comment]
Not a problem Boele! It was a pleasure working with you and I learned a whole lot from making this product. I am excited to see the new results! :)
Ruurd

**Pull request merged**
